### ISSUE TITLE
Move all things to the monorepo

### ISSUE THREAD

**Issue by taras** [bigtestjs/bigtest#1]
We would like to move all of the packages in BigTest into a single monorepo to make it easier to work on multiple packages at the same time. Once all of the projects are in the same repository, we'll be able to create a single PR that touches multiple packages. This issue will track a bunch of changes that we need to make.

## TODO

1. Move projects into this monorepo while preserving git history
   - [x] convergence
   - [x] interactor
   - [x] cli
   - [x] Setup yarn workspaces #33 
3. Automated Publishing
   - [ ] Add mechanism to automatically generate CHANGELOG (with emoji support)
   - [ ] Automatically publish preview builds
   - [ ] Automatically publish release builds
   - [ ] Write documentation about publishing conventions

**Comment by minkimcello** [comment]
Preview publishing is pretty straight forward but for releases we still need to decide how we want to update package version? Are we sticking with expect-user-to-update-version-manually?
